title: CCSC Central Plains 2025
preposition: at
description: >-
  Conference of the Consortium for Computing Sciences in Colleges, Central Plains Region 
  April 4th-5th, 2025 on the campus of Drake University in Des Moines, Iowa
baseurl: "/centralplains-new" # the subpath of your site, e.g. /blog
url: "https://www.ccsc.org" # the base hostname & protocol for your site, e.g. https://example.com

theme: jekyll-theme-conference

# Build settings
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - vendor
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/
  sessions:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room
  - scope:
      path: ""
      type: sessions
    values:
      layout: session


conference:

  # Language
  lang: en

  # Timezone
  tz: "+06:00"

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    logo: 
      name: CCSC Central Plains
      img: CCSC_Artboards_Color_Central-Plains-300x161.png
      url: 'https://www.ccsc.org/centralplains/'
    breakpoint: md
    links:
      - name: Program
        relative_url: /program/
      - name: Talks
        relative_url: /talks/
      - name: Speakers
        relative_url: /speakers/
      - name: Committee
        relative_url: /committee/
      - name: Travel
        menu:
        - name: Venue
          relative_url: /travel/venue/
        - name: Lodging
          relative_url: /travel/lodging/
      # - name: Previous Editions
      #   menu:
      #     - name: 2020 (current)
      #       disabled: true
      #     - name: 2019
      #       relative_url: /2019/
      #     - name: 2018
      #       relative_url: /2018/

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    # logo:
    #   img: ''
    links:
      - name: Program
        relative_url: /program/
      - name: How to get there
        relative_url: /travel/venue
      - name: Register
        disabled: false
        absolute_url: 'https://www.conftool.org/ccsc-cp/'

  # Information boxes
  #info_bars:
    # - title: We're getting ready for CCSC:CP 2025!
    #   color: primary
    #   main_only: true
    #   text: | 
    #     This program page will be updated as we get closer to the conference. Don't forget that until March 21st, you can still
    #     * [register](https://www.ccsc.org/centralplains/registration/) for the conference at the early rate
    #     * submit [lightning talks](https://www.ccsc.org/centralplains/presenters/) and works-in-progress 
    #     * sign up for the [student poster contest](https://www.ccsc.org/centralplains/poster-contest/), [student papers](https://www.ccsc.org/centralplains/studentpapers/), or the [student programming contest](https://www.ccsc.org/centralplains/programming-contest/)
    #- text: This is just some random content for demonstration purposes.
    #  color: warning
    #  pages_only: true


  # Live indications
  live:
    date: 01.01.2020
    timezone: GMT-6
    stop:       240  # in minutes
    streaming:
      enable: false
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  talks:
    # Talk categories
    main_categories:
      - name: Workshop
        color: info
      - name: Session
        color: primary
      - name: Panel
        color: success
      - name: Plenary
        color: secondary
      - name: Break
        color: warning
      - name: Student
        color: danger

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: false
    # URL of location / room overview page
    url: '/travel/venue'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page.  Set `map: false` if you don't want to
    # display it.
    map:
      # Initial map center point
      home_coord: 41.60312465593535, -93.65370619823557 #47.37808, 8.53935
      # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
      # The following do match the Bootstrap design not too badly:
      #   - Thunderforest.Neighbourhood
      #   - Esri.WorldTopoMap
      map_provider: "OpenStreetMap.Mapnik"
      default_zoom: 17
      pins:
      - coord: [41.60286546776129, -93.65362236369161]
        label: "Breakout Sessions - Collier-Scripps Hall"
      - coord: [41.60435998688192, -93.6513855711578]
        label: "Plenary Sessions and Meals - Shivers Hospitality Suite"
      - coord: [41.603718116549544, -93.65038963580994]
        label: "Park in this parking lot"
      - coord: [41.60144688663509, -93.653086832386]
        label: "Programming Contest - Carnegie Hall (upper level)"


  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true

